version: '3.8'

services:
  frontend:
    image: "${DOCKER_USERNAME}/image-fe:latest"
    ports:
      - "87:80"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    networks:
      - fe
      - be

networks:
  fe:
    driver: overlay
  be:
    external: true
