

services:
  frontend:
    image: "${DOCKER_USERNAME}/image-fe:latest"
    ports:
      - "80:80"
    deploy:
      replicas: 2
    networks:
      - fe
      - be  # Kết nối đến mạng be để giao tiếp với backend

networks:
  fe:
    driver: overlay
  be:
    external: true  # Mạng be đã được tạo trước đó
