
name: CI FE-APP

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove Old Image with Tag latest
        run: |
          echo "Removing old image with tag: latest"
          docker rmi ${{ secrets.DOCKER_USERNAME }}/image-fe:latest || true

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/image-fe:latest -f Dockerfile .

      - name: Push Docker Image
        run: |
          echo "Pushing image with tag: latest"
          docker push ${{ secrets.DOCKER_USERNAME }}/image-fe:latest

      - name: Send Email Notification
        if: success() || failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: '${{ job.status }}: Docker Image Push'
          body: 'The Docker image push step has ${{ job.status }}.'
          to: linhbeo5427@gmail.com
          from: sys@gmail.com

  pull_image:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: |
          echo "Pulling image with tag: latest"
          docker pull ${{ secrets.DOCKER_USERNAME }}/image-fe:latest

      - name: Send Email Notification
        if: success() || failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: '${{ job.status }}: Docker Image Pull'
          body: 'The Docker image pull step has ${{ job.status }}.'
          to: linhbeo5427@gmail.com
          from: sys@gmail.com

  test:
    runs-on: ubuntu-latest
    needs: pull_image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: |
          echo "Pulling image with tag: latest"
          docker pull ${{ secrets.DOCKER_USERNAME }}/image-fe:latest

      - name: Run Docker Container
        run: |
          echo "Stopping existing container if running"
          docker stop my-app-container || true
          docker rm my-app-container || true
          echo "Starting new container"
          docker run -d -p 3000:3000 --name my-app-container ${{ secrets.DOCKER_USERNAME }}/image-fe:latest

      - name: Check Application Status
        run: |
          echo "Checking application status"
          for i in {1..10}; do
            # Kiểm tra ứng dụng có thể truy cập trên port 3000
            if curl -s http://localhost:3000 | grep -q "Expected content"; then
              echo "The application is running successfully."
              exit 0
            fi
            echo "Application not ready yet, retrying in 10 seconds..."
            sleep 10
          done
          echo "The application failed to start."
          exit 1

      - name: Send Email Notification
        if: success() || failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: '${{ job.status }}: Deployment Status'
          body: 'The deployment step has ${{ job.status }}. The application is running.'
          to: linhbeo5427@gmail.com
          from: sys@gmail.com